# Generated by Django 5.2.5 on 2025-09-04 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "image",
                    models.ImageField(upload_to="media", verbose_name="Изображение"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("title_en", models.CharField(blank=True, verbose_name="Имя(англ.)")),
                ("title_jp", models.CharField(blank=True, verbose_name="Имя(япон.)")),
                (
                    "previous_pokemon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_pokemon",
                        to="pokemon_entities.pokemon",
                        verbose_name="Предыдущий покемон",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonEntity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField(verbose_name="Широта")),
                ("lon", models.FloatField(verbose_name="Долгота")),
                ("appeared_at", models.DateTimeField(verbose_name="Появится")),
                ("disappeared_at", models.DateTimeField(verbose_name="Исчезнет")),
                ("level", models.IntegerField(verbose_name="Уровень")),
                ("health", models.IntegerField(verbose_name="Здоровье")),
                ("strength", models.IntegerField(verbose_name="Сила")),
                ("defence", models.IntegerField(verbose_name="Защита")),
                ("stamina", models.IntegerField(verbose_name="Выносливость")),
                (
                    "pokemon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entities",
                        to="pokemon_entities.pokemon",
                        verbose_name="Покемон",
                    ),
                ),
            ],
        ),
    ]
