# Generated by Django 5.2.5 on 2025-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
