# Generated by Django 5.2.5 on 2025-09-02 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="pokemon_entities.pokemon",
                verbose_name="Покемон",
            ),
        ),
    ]
