# Generated by Django 5.2.5 on 2025-09-05 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="previous_pokemon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_pokemons",
                to="pokemon_entities.pokemon",
                verbose_name="Предыдущий покемон",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Имя(англ.)"
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Имя(япон.)"
            ),
        ),
    ]
