# Generated by Django 5.2.5 on 2025-09-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_entities",
            "0002_pokemonentity_description_alter_pokemon_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="title_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="title_jp",
            field=models.TextField(null=True),
        ),
    ]
