# Generated by Django 5.2.5 on 2025-09-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0002_pokemon_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
