# Generated by Django 5.2.5 on 2025-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0003_pokemonentity_title_en_pokemonentity_title_jp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemonentity",
            name="description",
        ),
        migrations.RemoveField(
            model_name="pokemonentity",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="pokemonentity",
            name="title_jp",
        ),
        migrations.AddField(
            model_name="pokemon",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_jp",
            field=models.TextField(null=True),
        ),
    ]
