# Generated by Django 5.2.5 on 2025-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0003_alter_pokemon_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="title",
            field=models.CharField(default="default title"),
        ),
    ]
