# Generated by Django 5.2.5 on 2025-09-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0004_alter_pokemon_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="image",
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
