# Generated by Django 5.2.5 on 2025-09-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0004_remove_pokemonentity_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="previous_pokemon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pokemon_entities.pokemon",
            ),
        ),
    ]
