# Generated by Django 5.2.5 on 2025-09-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0005_remove_pokemon_image_alter_pokemon_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
