# Generated by Django 5.2.5 on 2025-09-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0006_pokemon_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="level",
        ),
    ]
