# Generated by Django 5.2.5 on 2025-09-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0007_remove_pokemon_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
