# Generated by Django 5.2.5 on 2025-09-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0008_pokemon_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="photo",
        ),
    ]
