# Generated by Django 5.2.5 on 2025-09-03 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0009_alter_pokemon_previous_pokemon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="previous_pokemon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_pokemon",
                to="pokemon_entities.pokemon",
            ),
        ),
    ]
