# Generated by Django 5.2.5 on 2025-09-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0009_remove_pokemon_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
