# Generated by Django 5.2.5 on 2025-09-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0010_alter_pokemon_previous_pokemon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="previous_pokemon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_pokemon",
                to="pokemon_entities.pokemon",
                verbose_name="Предыдущий покемон",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_en",
            field=models.TextField(blank=True, null=True, verbose_name="Имя(англ.)"),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_jp",
            field=models.TextField(blank=True, null=True, verbose_name="Имя(япон.)"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(null=True, verbose_name="Появится"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="defence",
            field=models.IntegerField(null=True, verbose_name="Защита"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(null=True, verbose_name="Исчезнет"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="health",
            field=models.IntegerField(null=True, verbose_name="Здоровье"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="lat",
            field=models.FloatField(null=True, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="level",
            field=models.IntegerField(null=True, verbose_name="Уровень"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="lon",
            field=models.FloatField(null=True, verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="stamina",
            field=models.IntegerField(null=True, verbose_name="Выносливость"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="strength",
            field=models.IntegerField(null=True, verbose_name="Сила"),
        ),
    ]
